# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
DISABLE_LINTERS:
  - PYTHON_BLACK

CLEAR_REPORT_FOLDER: true

SPELL_CSPELL_ANALYZE_FILE_NAMES: false

PRE_COMMANDS:
  - continue_if_failed: false
    cwd: workspace
    command: apk update && apk add sdl2-dev py3-pygame
  - continue_if_failed: false
    cwd: workspace
    command: pip install -r requirements.txt
  # - continue_if_failed: false
  #   cwd: workspace
  #   command: poetry install --group dev
